### ISSUE TITLE
Diakritika

### ISSUE THREAD

**Issue by ArcanumSK** [AntreTeam/TheGame#1]
Diakritika v readme https://github.com/AntreTeam/TheGame/blob/master/README.md je dosť rozbitá, neviem čím to je opravi´t alebo nepouzivat nikde diakritiku.

**Comment by j2ghz** [comment]
Nepouzivat diakritiku, vzhledem k tomu v kolika ruznych programech a na ruznych OS se to bude otvirat

**Comment by ArcanumSK** [comment]
Tak nech tam neni ten hnusny rozbity text v readme :D

**Comment by j2ghz** [comment]
odmitam, u me to zobrazuje dobre
