### ISSUE TITLE
Double refresh?

### ISSUE THREAD

**Issue by j2ghz** [AntreTeam/TheGame#12]
Kdyz kliknu na koupit tak stranka zmizi, pak se objevi kus aktualizovane, pak zmizi a pak se zase objevi
je to velmi rychle jen takove probliknuti ale chtelo by to vymyslet nejak ze se budou jen menit veci na te strance ne ze se cela vykresli znova
zni to jako ze by to stacilo ve final verzi ale ja myslim ze by bylo lepsi s tim pocitat a met to tak udelane uz od zacatku (i kdyz nemusim mit pravdu o php toho mnoho nevim)

**Comment by opuro** [comment]
Nechal bych to zatím tak ať to jura a ostatní udělají jak umí, pak to můžu/můžeme zkusit předělat na AJAX (hlavní změny: místo echo budeme generovat javascriptem html string, který se tam vloží, a ten html string se může obnovovat aniž by se refreshla stránka)

**Comment by j2ghz** [comment]
Nevim jak se to dela, jen aby to nedopadlo pak tak ze bude velky projekt a na konci jak robot budes kazde jedno vraceni hodnoty upravovat
Pokud by se to melo stat tak si myslim ze je to lepsi resit, treba nemusi byt hned ale brzo
