### ISSUE TITLE
Jazyk

### ISSUE THREAD

**Issue by ArcanumSK** [AntreTeam/TheGame#2]
Čo sa jazyka celkovo týka, skúste sa vyjadriť aký by sme mali používať v kóde a v dokumentácii. (podľa možností jeden) každopádne Frontend MUSÍ byť SLOVENSKY, tam neexistuje kompromis.

**Comment by j2ghz** [comment]
ja bych to nechal na jurovi, jelikoz toho asi udela nejvic

**Comment by j2ghz** [comment]
opravil sem par veci v bb268b3fe889d90cbf87029fcc99806e2e21ddb9 ale asi to budes muset delat ty @ArcanumSK ja sem obcas tipoval

**Comment by ArcanumSK** [comment]
Ja to budu delat, a v podstate mi je zbytek jazyka jedno nech je ale jeden + rozrhanine  slovensky...

**Comment by ArcanumSK** [comment]
NO tak ja to proste na oknci projdu a prelozim....
