### ISSUE TITLE
Kód na GH

### ISSUE THREAD

**Issue by ArcanumSK** [AntreTeam/TheGame#3]
Aktuálny kód vždy na GH, taktiež pracovať s kódom, ktorý je aktuálny. Tzn, ak niečo commitnem do kódu a bude to logicky njaký enhancment alebo oprava čokoľvek tak počítam že sa tá zmena aj použije v developmente.... Nieže si budé kaž´d ypracovať zo svojou verziou kódu (samozrejme forky sú niečo iné, ale ak existuje nejaký iný branch ako je na GH, tka nech tam je a je o ňom vedieť...

**Comment by j2ghz** [comment]
ja to tam budu davat vzdy, ty taky, jura rikal ze vzdy kdyz to nebude rozbite a to je vse ne?
