### ISSUE TITLE
Test server Latest build

### ISSUE THREAD

**Issue by ArcanumSK** [AntreTeam/TheGame#4]
Exstuje nejaky spôsob ako amt vzdy na nejakom serveri latest verziu automaticky ? Prida sa nejaky updater do toho napriklad ? Ze by si to vzdy soslo realease odtialto ? Jozo skus sa na to pozriet s Jirvozom (ak dojdete na to ze len manualne tak to neni zas taky problem, ak bduete potrebovat server mam vela dajte vediet...)

**Comment by j2ghz** [comment]
nejnovejsi verze bude vzdy na http://antre.417rct.org/, ted jen doresit databazi

**Comment by j2ghz** [comment]
to je trapne ze nejde dat 2 naraz

**Comment by ArcanumSK** [comment]
Jo je, a databaze je poresena, jak sa zmeni tak ju proste manulane inportuju pres phpMyAdmina

**Comment by ArcanumSK** [comment]
Tak jako @j2ghz ?

**Comment by j2ghz** [comment]
az budu met cas tak to opravim

**Comment by j2ghz** [comment]
solved 570144236dfe00fed2c8b2bb3b0431334c6154e0 http://antre.417rct.org/
