### ISSUE TITLE
JavaScript hash knihovna

### ISSUE THREAD

**Issue by opuro** [AntreTeam/TheGame#9]
https://code.google.com/p/crypto-js/ knihovna pro hashování přes JavaScript, aby se přes POST neposílalo nic surové...

**Comment by j2ghz** [comment]
pozor:
>Inactivity

>CryptoJS is a project that I enjoy and work on in my spare time, but unfortunately my 9-to-5 hasn't left me with as much free time as it used to. I'd still like to continue improving it in the future, but I can't say when that will be. If you find that CryptoJS doesn't meet your needs, then I'd recommend you try Forge https://github.com/digitalbazaar/forge.
